### PR TITLE
Close issue 3 - Update nodejs build dependency version

### PR DESCRIPTION
**Pull request by cknoblauch**

### CODE REVIEW

**Comment by micwoj92** [comment]
Solved, can be closed.

**Comment by cknoblauch** [comment]
I *think* the pkgrel needs to be incremented every time the PKGBUILD changes, even if the version remains the same, on indicate that something changed. I may be mistaken though, let me know and I'll close the PR if that's the case.

**Comment by micwoj92** [comment]
From Arch wiki
"As fixes and additional features are added to the PKGBUILD that influence
the resulting package, the pkgrel should be incremented by 1."

I don't think so, if it was dependency, then yes. Makedep does not
influence the package.




W dniu środa, 7 lipca 2021 cknoblauch ***@***.***> napisał(a):
> I think the pkgrel needs to be incremented every time the PKGBUILD
changes, even if the version remains the same, on indicate that something
changed. I may be mistaken though, let me know and I'll close the PR if
that's the case.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/ZBperBQUESgHCQO7uprPUd-CCD0ZRAJfiCS5SHQsLHAkEr-iGCzm3RzNlK2mhQgK7kfsK5QUrQo4DEBEDmRqFeDnWnQP5EQXuJpk3USYyHnBj8mx0h0_MxOK1LxNVP5Vz237-XRXVUNuXJBJd8nK3W8wTJ9vLFz_es44mIaA25VRdGDrDfoikonI389kmMHKsvslraQkdzAiNkPn1IJOFWfSFkCgw3DV_BC0MwBKAw=s0-d-e1-ft#https://github.com/notifications/beacon/AK3YG4RPXGG6TRJIVKLJ323TWPEFTA5CNFSM4723KAUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGQVT4IQ.gif>

**Comment by cknoblauch** [comment]
Ok thanks for the clarification. I'm closing the PR.

**Pull request closed without merging**
